config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/image_chooser', to: 'ideas#chooser'


  resources :users, only: [:new, :create, :show] do
    resources :ideas, only: [:index, :new, :create, :show, :destroy, :edit, :update]
  end

  namespace :admin do
    resources :categories, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :images, only: [:index, :new, :create, :destroy, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :topic
  has_many :ideas
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates_presence_of :title, :image, :note
  belongs_to :category, optional: true
  belongs_to :user
  has_many :ideaimages
  has_many :ideas, through: :ideaimages
end

app/models/ideaimages.rb
class IdeaImages < ApplicationRecord
  belongs_to :ideas
  belongs_to :images
end

app/models/image.rb
class Image < ApplicationRecord
  validates_presence_of :url
  validates_presence_of :description
  has_many :ideaimages
  has_many :ideas, through: :ideaimages
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates_presence_of :password, require: true
  has_many :ideas

  has_secure_password

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(category_params)
    category.save
    redirect_to admin_categories_path
  end

  def edit

  end

  def update
    @category.update(category_params)
    redirect_to admin_categories_path
  end

  def destroy
    @category = Category.destroy(params[:id])
    redirect_to admin_categories_path
  end

  private
    def category_params
      params.require(:category).permit(:topic)
    end

    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController
  before_action :set_image, only: [:edit, :update]

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    image = Image.new(image_params)
    image.save
    redirect_to admin_images_path
  end

  def edit

  end

  def update
    @image.update(image_params)
    redirect_to admin_images_path
  end

  def destroy
    @image = Image.destroy(params[:id])
    redirect_to admin_images_path
  end

  private
    def image_params
      params.require(:image).permit(:url, :description)
    end

    def set_image
      @image = Image.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to categories_path
  end

  def edit

  end

  def update
    @category.update(category_params)
    redirect_to categories_path
  end

  def destroy
    @category = Category.destroy(params[:id])
    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:topic)
    end

    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:edit, :update]

  def index
    @ideas = Idea.all
  end

  def new
    @idea = Idea.new
    @user = User.find(params[:user_id])
  end

  def create
    user = User.find(params[:user_id])
    idea = user.ideas.new(idea_params)
    idea.save
    redirect_to user_path(current_user)
  end

  def edit
    @user = current_user
  end

  def update
    @idea.update(idea_params)
    redirect_to user_path(current_user)
  end

  def destroy
    @idea = Idea.destroy(params[:id])
    redirect_to user_path(current_user)
  end

  def chooser
    # render :chooser
    # @idea.update(idea_params)
    redirect_to user_path(current_user)
  end

  private
    def idea_params
      params.require(:idea).permit(:title, :image, :note)
    end

    def set_idea
      @idea = Idea.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:username, :password)
    end

    def require_login

    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
<%= f.label "Topic" %>
<%= f.text_field :topic %>
<%= f.submit %>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Edit a Category</h1>
</br>
<%= render partial: '/layouts/nav' %>
</br>
<%= render partial: 'form' %>

app/views/admin/categories/index.html.erb
<h1>Categories</h1>
</br>
<%= render partial: '/layouts/nav' %>
</br>
<%= link_to "Create a New Category", new_admin_category_path %>
</br></br>
<% @categories.each do |cat| %>
  <div class="modify">
    <p>
      <%= cat.topic %>
    </p>
    <%= link_to "Edit", edit_admin_category_path(cat) %>
    <%= link_to "Delete", admin_category_path(cat), method: :delete %>
  </div>
<% end %>

app/views/admin/categories/new.html.erb
<h1>Create New Category</h1>
</br>
<%= render partial: '/layouts/nav' %>
</br>
<%= render partial: 'admin/categories/form' %>

app/views/admin/images/_form.html.erb
<%= form_for [:admin, @image] do |f| %>
<%= f.label "Image URL" %>
<%= f.text_field :url %>
<%= f.label "Image Description" %>
<%= f.text_field :description %>
<%= f.submit %>
<% end %>

app/views/admin/images/edit.html.erb
<h1>Edit an Image</h1>
</br>
<%= render partial: '/layouts/nav' %>
</br>
<%= render partial: 'form' %>

app/views/admin/images/index.html.erb
<h1>Images</h1>
</br>
<%= render partial: '/layouts/nav' %>
</br>
<%= link_to "Create a New Image", new_admin_image_path %>
</br></br>
<% @images.each do |pic| %>
  <div class="modify">
    <ul>
      <li><img src="<%= pic.url %>"</li>
      <li><%= pic.description %></li>
    </ul>
    <%= link_to "Edit", edit_admin_image_path(pic) %>
    <%= link_to "Delete", admin_image_path(pic), method: :delete %>
  </div>
<% end %>

app/views/admin/images/new.html.erb
<h1>Create a New Image</h1>
</br>
<%= render partial: '/layouts/nav' %>
</br>
<%= render partial: 'admin/images/form' %>

app/views/ideas/_form.html.erb
<%= form_for [@user, @idea] do |f| %>
<%= f.label "Title" %>
<%= f.text_field :title %>
<!-- <%= link_to "Choose an Image", image_chooser_path %> -->
<%= f.label "Image" %>
<%= f.text_field :image %>
<%= f.label :category %>
<%= f.collection_select :category_id, Category.all, :id, :topic %>
<%= f.label "Note" %>
<%= f.text_field :note %>
<%= f.submit %>
<% end %>

app/views/ideas/chooser.html.erb
<%= form_for @idea do |f| %>
<%= f.label :image %>
<!-- <%= f.select(:TYPE, Images.collect {|p| [ p.url, p.id ] },
                                          { :prompt => "Please select"},
                                          { :multiple => true, :size => 5 }) %> -->
<% @images.each do |pic| %>
<img src="<%= pic.url %>">
<%= options_for_select([pic.url, (pic.index + 1)]) %>
<% end %>
<%= f.submit %>
<% end %>

app/views/ideas/edit.html.erb
<h1>Edit an Idea</h1>
<%= render partial: '/layouts/nav' %>
</br>
<%= render partial: 'form' %>

app/views/ideas/index.html.erb
<h1>Ideas</h1>
</br>
<%= render partial: '/layouts/nav' %>
</br>

app/views/ideas/new.html.erb
<h1>Create A New Idea</h1>
</br>
<%= render partial: '/layouts/nav' %>
</br>
<h2>Type Your Information Here:</h2>
</br>
<%= render partial: 'form' %>

app/views/ideas/show.html.erb
</br>
<%= render partial: '/layouts/nav' %>
</br>

app/views/layouts/_nav.html.erb
<div class="nav">
<p>Logged in as, <%= current_user.username %></p>
</br>
<%= link_to "Home", user_path(current_user) %> </br>
</br>
<%= link_to "Create a New Idea", new_user_idea_path(current_user) %> </br>
</br>
<%= link_to "Category Corner", admin_categories_path if current_user.admin? %>
</br></br>
<%= link_to "Image Corner", admin_images_path if current_user.admin? %>
</br></br>
<%= link_to "Log Out", logout_path %>
</br>
</div>
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideabox</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps:700|Ubuntu" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Simonetta:900" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="main_div">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= current_user.username %>'s Homepage</h1>
</br>
<%= render partial: '/layouts/nav' %>
</br></br>
<% @user.ideas.each do |idea| %>
  <div class="modify">
    <ul>
      <li><%= link_to "#{idea.title}", user_idea_path(@user, idea) %></li>
      <li><img src="<%= idea.image %>" alt ="box pic"></li>
      <li><%= link_to "Change Photo", image_chooser_path %></li>
      <li><%= idea.note %></li>
    </ul>
    <%= link_to "Edit", edit_user_idea_path(@user, idea) %>
    <%= link_to "Delete", user_idea_path(@user, idea), method: :delete %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to IdeaBox</h1>
<img src="https://www.boxedinn.com/wp-content/uploads/boxed-inn-12x9x6-shipping-box.jpg" alt="box pic" />
<h2>Where all the Boxes Go to Become Ideas</h2>

<%= link_to "Sign Up to Be a User", new_user_path %> </br></br>
<%= link_to "Sign In", login_path %>